repos:
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Use the latest version of flake8 at the time
    hooks:
      - id: flake8
        args:
          - --count
          - --select=E9,F63,F7,F82
          - --show-source
          - --statistics